// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart_Farm.Models;

#nullable disable

namespace Smart_Farm.Migrations
{
    [DbContext(typeof(farContext))]
    [Migration("20260414025037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CROP_FERTILIZER", b =>
                {
                    b.Property<int>("FrId")
                        .HasColumnType("int");

                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.HasKey("FrId", "Cid")
                        .HasName("PK__CROP_FER__3EAB9A937EDA9D18");

                    b.HasIndex("Cid");

                    b.ToTable("CROP_FERTILIZER", (string)null);
                });

            modelBuilder.Entity("Smart_Farm.Models.AI_Diagnosis", b =>
                {
                    b.Property<int>("ADid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ADid"));

                    b.Property<int?>("Cid")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DiagnosisDate")
                        .HasColumnType("date");

                    b.Property<int?>("Did")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ADid")
                        .HasName("PK__AI_Diagn__7931D1B8DEB8ED6F");

                    b.HasIndex("Cid");

                    b.HasIndex("Did");

                    b.ToTable("AI_Diagnosis");
                });

            modelBuilder.Entity("Smart_Farm.Models.BELONG_TO", b =>
                {
                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Harvest_Time")
                        .HasColumnType("date");

                    b.Property<int?>("Plant_count")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Sow_Time")
                        .HasColumnType("date");

                    b.HasKey("Cid", "Pid")
                        .HasName("PK__BELONG_T__5DA8DDF25F4CF032");

                    b.HasIndex("Pid");

                    b.ToTable("BELONG_TO");
                });

            modelBuilder.Entity("Smart_Farm.Models.COMPATIBILITY", b =>
                {
                    b.Property<int>("FrId")
                        .HasColumnType("int");

                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("FrId", "Pid")
                        .HasName("PK__COMPATIB__AEE362867FBB5969");

                    b.HasIndex("Pid");

                    b.ToTable("COMPATIBILITY");
                });

            modelBuilder.Entity("Smart_Farm.Models.CROP", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cid"));

                    b.Property<decimal?>("Area_size")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Current_Stage")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Soil_type")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("Start_date")
                        .HasColumnType("date");

                    b.Property<int?>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Cid")
                        .HasName("PK__CROP__C1FFD8616FF697CD");

                    b.HasIndex("Uid");

                    b.ToTable("CROP");
                });

            modelBuilder.Entity("Smart_Farm.Models.Disease", b =>
                {
                    b.Property<int>("Did")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Did"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nause")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Treatment")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Did")
                        .HasName("PK__Disease__C03122188275DDE5");

                    b.ToTable("Disease");
                });

            modelBuilder.Entity("Smart_Farm.Models.FERTILIZER", b =>
                {
                    b.Property<int>("FrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Fertilizer_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("FrId")
                        .HasName("PK__FERTILIZ__32B46715A38ED2B3");

                    b.ToTable("FERTILIZER");
                });

            modelBuilder.Entity("Smart_Farm.Models.GROWS_IN", b =>
                {
                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.Property<string>("Plant_in_season_description")
                        .HasColumnType("text");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Pid", "Sid")
                        .HasName("PK__GROWS_IN__59D1BCEFD9462B22");

                    b.HasIndex("Sid");

                    b.ToTable("GROWS_IN");
                });

            modelBuilder.Entity("Smart_Farm.Models.IRRIGATION", b =>
                {
                    b.Property<int>("Iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iid"));

                    b.Property<int?>("Cid")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Frequency_unit")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("Frequency_value")
                        .HasColumnType("int");

                    b.Property<string>("Irrigation_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Sis")
                        .HasColumnType("int");

                    b.Property<decimal?>("Water_amount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Iid")
                        .HasName("PK__IRRIGATI__C4962F8429AE39D0");

                    b.HasIndex("Cid");

                    b.HasIndex("Sis");

                    b.ToTable("IRRIGATION");
                });

            modelBuilder.Entity("Smart_Farm.Models.IRRIGATION_STAGE", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sid"));

                    b.Property<int?>("Cid")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name_stage")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Stage_order")
                        .HasColumnType("int");

                    b.HasKey("Sid")
                        .HasName("PK__IRRIGATI__CA1E5D78AA21B4A3");

                    b.HasIndex("Cid");

                    b.ToTable("IRRIGATION_STAGE");
                });

            modelBuilder.Entity("Smart_Farm.Models.ORDER", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Oid"));

                    b.Property<DateOnly?>("Order_date")
                        .HasColumnType("date");

                    b.Property<int?>("Pid")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Total_price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Oid")
                        .HasName("PK__ORDERS__CB3E4F31B009E3AD");

                    b.HasIndex("Pid");

                    b.HasIndex("Uid");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("Smart_Farm.Models.PLANT", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pid"));

                    b.Property<int?>("Days_to_harvest")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Fertilizer_need")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Humidity_range")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Seed_type")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Soil_type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Temperature_range")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Water_need")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Pid")
                        .HasName("PK__PLANT__C5705938049F0DBC");

                    b.ToTable("PLANT");
                });

            modelBuilder.Entity("Smart_Farm.Models.PRODUCT", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pid"));

                    b.Property<DateOnly?>("Added_date")
                        .HasColumnType("date");

                    b.Property<int?>("Cid")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Pid")
                        .HasName("PK__PRODUCT__C5705938F6FC9017");

                    b.HasIndex("Cid");

                    b.HasIndex("Uid");

                    b.ToTable("PRODUCT");
                });

            modelBuilder.Entity("Smart_Farm.Models.SEASON", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sid"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Sid")
                        .HasName("PK__SEASON__CA1E5D786783D710");

                    b.ToTable("SEASON");
                });

            modelBuilder.Entity("Smart_Farm.Models.Task", b =>
                {
                    b.Property<int>("Task_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Task_id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Task_id")
                        .HasName("PK__Task__716846B5F30205F9");

                    b.HasIndex("Uid");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("Smart_Farm.Models.USER", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("Address_line")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("City_name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("First_name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Last_name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<string>("PasswordHashed")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Uid")
                        .HasName("PK__USERS__C5B69A4A9CA97C86");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Smart_Farm.Models.USER_PHONE", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Phone", "Uid")
                        .HasName("PK__USER_PHO__E0255C3B7CD4D930");

                    b.HasIndex("Uid");

                    b.ToTable("USER_PHONE");
                });

            modelBuilder.Entity("CROP_FERTILIZER", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", null)
                        .WithMany()
                        .HasForeignKey("Cid")
                        .IsRequired()
                        .HasConstraintName("FK__CROP_FERTIL__Cid__5812160E");

                    b.HasOne("Smart_Farm.Models.FERTILIZER", null)
                        .WithMany()
                        .HasForeignKey("FrId")
                        .IsRequired()
                        .HasConstraintName("FK__CROP_FERTI__FrId__571DF1D5");
                });

            modelBuilder.Entity("Smart_Farm.Models.AI_Diagnosis", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", "CidNavigation")
                        .WithMany("AI_Diagnoses")
                        .HasForeignKey("Cid")
                        .HasConstraintName("FK__AI_Diagnosi__Cid__6754599E");

                    b.HasOne("Smart_Farm.Models.Disease", "DidNavigation")
                        .WithMany("AI_Diagnoses")
                        .HasForeignKey("Did")
                        .HasConstraintName("FK__AI_Diagnosi__Did__68487DD7");

                    b.Navigation("CidNavigation");

                    b.Navigation("DidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.BELONG_TO", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", "CidNavigation")
                        .WithMany("BELONG_TOs")
                        .HasForeignKey("Cid")
                        .IsRequired()
                        .HasConstraintName("FK__BELONG_TO__Cid__4D94879B");

                    b.HasOne("Smart_Farm.Models.PLANT", "PidNavigation")
                        .WithMany("BELONG_TOs")
                        .HasForeignKey("Pid")
                        .IsRequired()
                        .HasConstraintName("FK__BELONG_TO__Pid__4E88ABD4");

                    b.Navigation("CidNavigation");

                    b.Navigation("PidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.COMPATIBILITY", b =>
                {
                    b.HasOne("Smart_Farm.Models.FERTILIZER", "Fr")
                        .WithMany("COMPATIBILITies")
                        .HasForeignKey("FrId")
                        .IsRequired()
                        .HasConstraintName("FK__COMPATIBIL__FrId__5AEE82B9");

                    b.HasOne("Smart_Farm.Models.PLANT", "PidNavigation")
                        .WithMany("COMPATIBILITies")
                        .HasForeignKey("Pid")
                        .IsRequired()
                        .HasConstraintName("FK__COMPATIBILI__Pid__5BE2A6F2");

                    b.Navigation("Fr");

                    b.Navigation("PidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.CROP", b =>
                {
                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany("CROPs")
                        .HasForeignKey("Uid")
                        .HasConstraintName("FK__CROP__Uid__4316F928");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.GROWS_IN", b =>
                {
                    b.HasOne("Smart_Farm.Models.PLANT", "PidNavigation")
                        .WithMany("GROWS_INs")
                        .HasForeignKey("Pid")
                        .IsRequired()
                        .HasConstraintName("FK__GROWS_IN__Pid__5165187F");

                    b.HasOne("Smart_Farm.Models.SEASON", "SidNavigation")
                        .WithMany("GROWS_INs")
                        .HasForeignKey("Sid")
                        .IsRequired()
                        .HasConstraintName("FK__GROWS_IN__Sid__52593CB8");

                    b.Navigation("PidNavigation");

                    b.Navigation("SidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.IRRIGATION", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", "CidNavigation")
                        .WithMany("IRRIGATIONs")
                        .HasForeignKey("Cid")
                        .HasConstraintName("FK__IRRIGATION__Cid__628FA481");

                    b.HasOne("Smart_Farm.Models.IRRIGATION_STAGE", "SisNavigation")
                        .WithMany("IRRIGATIONs")
                        .HasForeignKey("Sis")
                        .HasConstraintName("FK__IRRIGATION__Sis__619B8048");

                    b.Navigation("CidNavigation");

                    b.Navigation("SisNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.IRRIGATION_STAGE", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", "CidNavigation")
                        .WithMany("IRRIGATION_STAGEs")
                        .HasForeignKey("Cid")
                        .HasConstraintName("FK__IRRIGATION___Cid__5EBF139D");

                    b.Navigation("CidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.ORDER", b =>
                {
                    b.HasOne("Smart_Farm.Models.PRODUCT", "PidNavigation")
                        .WithMany("ORDERs")
                        .HasForeignKey("Pid")
                        .HasConstraintName("FK__ORDERS__Pid__49C3F6B7");

                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany("ORDERs")
                        .HasForeignKey("Uid")
                        .HasConstraintName("FK__ORDERS__Uid__4AB81AF0");

                    b.Navigation("PidNavigation");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.PRODUCT", b =>
                {
                    b.HasOne("Smart_Farm.Models.CROP", "CidNavigation")
                        .WithMany("PRODUCTs")
                        .HasForeignKey("Cid")
                        .HasConstraintName("FK__PRODUCT__Cid__46E78A0C");

                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany("PRODUCTs")
                        .HasForeignKey("Uid")
                        .HasConstraintName("FK__PRODUCT__Uid__45F365D3");

                    b.Navigation("CidNavigation");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.Task", b =>
                {
                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("Uid")
                        .HasConstraintName("FK__Task__Uid__3C69FB99");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.USER_PHONE", b =>
                {
                    b.HasOne("Smart_Farm.Models.USER", "UidNavigation")
                        .WithMany("USER_PHONEs")
                        .HasForeignKey("Uid")
                        .IsRequired()
                        .HasConstraintName("FK__USER_PHONE__Uid__398D8EEE");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Smart_Farm.Models.CROP", b =>
                {
                    b.Navigation("AI_Diagnoses");

                    b.Navigation("BELONG_TOs");

                    b.Navigation("IRRIGATION_STAGEs");

                    b.Navigation("IRRIGATIONs");

                    b.Navigation("PRODUCTs");
                });

            modelBuilder.Entity("Smart_Farm.Models.Disease", b =>
                {
                    b.Navigation("AI_Diagnoses");
                });

            modelBuilder.Entity("Smart_Farm.Models.FERTILIZER", b =>
                {
                    b.Navigation("COMPATIBILITies");
                });

            modelBuilder.Entity("Smart_Farm.Models.IRRIGATION_STAGE", b =>
                {
                    b.Navigation("IRRIGATIONs");
                });

            modelBuilder.Entity("Smart_Farm.Models.PLANT", b =>
                {
                    b.Navigation("BELONG_TOs");

                    b.Navigation("COMPATIBILITies");

                    b.Navigation("GROWS_INs");
                });

            modelBuilder.Entity("Smart_Farm.Models.PRODUCT", b =>
                {
                    b.Navigation("ORDERs");
                });

            modelBuilder.Entity("Smart_Farm.Models.SEASON", b =>
                {
                    b.Navigation("GROWS_INs");
                });

            modelBuilder.Entity("Smart_Farm.Models.USER", b =>
                {
                    b.Navigation("CROPs");

                    b.Navigation("ORDERs");

                    b.Navigation("PRODUCTs");

                    b.Navigation("Tasks");

                    b.Navigation("USER_PHONEs");
                });
#pragma warning restore 612, 618
        }
    }
}
