// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[PrimaryKey("Cid", "Pid")]
[Table("BELONG_TO")]
public partial class BELONG_TO
{
    public int? Plant_count { get; set; }

    public DateOnly? Sow_Time { get; set; }

    public DateOnly? Harvest_Time { get; set; }

    [Key]
    public int Cid { get; set; }

    [Key]
    public int Pid { get; set; }

    [ForeignKey("Cid")]
    [InverseProperty("BELONG_TOs")]
    public virtual CROP CidNavigation { get; set; }

    [ForeignKey("Pid")]
    [InverseProperty("BELONG_TOs")]
    public virtual PLANT PidNavigation { get; set; }
}