// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[PrimaryKey("FrId", "Pid")]
[Table("COMPATIBILITY")]
public partial class COMPATIBILITY
{
    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Rate { get; set; }

    [Key]
    public int FrId { get; set; }

    [Key]
    public int Pid { get; set; }

    [ForeignKey("FrId")]
    [InverseProperty("COMPATIBILITies")]
    public virtual FERTILIZER Fr { get; set; }

    [ForeignKey("Pid")]
    [InverseProperty("COMPATIBILITies")]
    public virtual PLANT PidNavigation { get; set; }
}