// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("Disease")]
public partial class Disease
{
    [Key]
    public int Did { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Nause { get; set; }

    [StringLength(100)]
    public string Symptoms { get; set; }

    [StringLength(100)]
    public string Treatment { get; set; }

    [InverseProperty("DidNavigation")]
    public virtual ICollection<AI_Diagnosis> AI_Diagnoses { get; set; } = new List<AI_Diagnosis>();
}