// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("FERTILIZER")]
public partial class FERTILIZER
{
    [Key]
    public int FrId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Amount { get; set; }

    [StringLength(20)]
    public string Unit { get; set; }

    [StringLength(100)]
    public string Method { get; set; }

    [StringLength(100)]
    public string Fertilizer_name { get; set; }

    [InverseProperty("Fr")]
    public virtual ICollection<COMPATIBILITY> COMPATIBILITies { get; set; } = new List<COMPATIBILITY>();

    [ForeignKey("FrId")]
    [InverseProperty("Frs")]
    public virtual ICollection<CROP> Cids { get; set; } = new List<CROP>();
}