// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[PrimaryKey("Pid", "Sid")]
[Table("GROWS_IN")]
public partial class GROWS_IN
{
    [Column(TypeName = "nvarchar(max)")]
    public string Plant_in_season_description { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Rate { get; set; }

    [Key]
    public int Pid { get; set; }

    [Key]
    public int Sid { get; set; }

    [ForeignKey("Pid")]
    [InverseProperty("GROWS_INs")]
    public virtual PLANT PidNavigation { get; set; }

    [ForeignKey("Sid")]
    [InverseProperty("GROWS_INs")]
    public virtual SEASON SidNavigation { get; set; }
}