// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("ORDERS")]
public partial class ORDER
{
    [Key]
    public int Oid { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public DateOnly? Order_date { get; set; }

    public int? Quantity { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Total_price { get; set; }

    public int? Pid { get; set; }

    public int? Uid { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Payment_method { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Promo_code { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Discount_amount { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Order_notes { get; set; }

    public DateTime CreatedAt { get; set; }

    [ForeignKey("Pid")]
    [InverseProperty("ORDERs")]
    public virtual PRODUCT PidNavigation { get; set; }

    [ForeignKey("Uid")]
    [InverseProperty("ORDERs")]
    public virtual USER UidNavigation { get; set; }
}