// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("PRODUCT")]
public partial class PRODUCT
{
    [Key]
    public int Pid { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Description { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    public DateOnly? Added_date { get; set; }

    public int? Quantity { get; set; }

    public int? Uid { get; set; }

    public int? Cid { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Category { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string ImageUrl { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string ImageGalleryJson { get; set; }

    public double? Rating { get; set; }

    [InverseProperty("PidNavigation")]
    public virtual ICollection<PRODUCT_IMAGE> PRODUCT_IMAGEs { get; set; } = new List<PRODUCT_IMAGE>();

    [ForeignKey("Cid")]
    [InverseProperty("PRODUCTs")]
    public virtual CROP CidNavigation { get; set; }

    [InverseProperty("PidNavigation")]
    public virtual ICollection<ORDER> ORDERs { get; set; } = new List<ORDER>();

    [ForeignKey("Uid")]
    [InverseProperty("PRODUCTs")]
    public virtual USER UidNavigation { get; set; }
}