// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("SEASON")]
public partial class SEASON
{
    [Key]
    public int Sid { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Description { get; set; }

    [InverseProperty("SidNavigation")]
    public virtual ICollection<GROWS_IN> GROWS_INs { get; set; } = new List<GROWS_IN>();
}