// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[Table("Task")]
public partial class Task
{
    [Key]
    public int Task_id { get; set; }

    public DateOnly? Date { get; set; }

    [StringLength(100)]
    public string Label { get; set; }

    [Column(TypeName = "nvarchar(max)")]
    public string Content { get; set; }

    [StringLength(50)]
    public string State { get; set; }

    public int? Uid { get; set; }

    public DateTime CreatedAt { get; set; }

    [ForeignKey("Uid")]
    [InverseProperty("Tasks")]
    public virtual USER UidNavigation { get; set; }
}