// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Smart_Farm.Models;

[PrimaryKey("Phone", "Uid")]
[Table("USER_PHONE")]
public partial class USER_PHONE
{
    [Key]
    [StringLength(20)]
    public string Phone { get; set; }

    [Key]
    public int Uid { get; set; }

    [ForeignKey("Uid")]
    [InverseProperty("USER_PHONEs")]
    public virtual USER UidNavigation { get; set; }
}